Create Database Studentdata;
USE Studentdata;
CREATE TABLE STUDENTS(
STUDENTID INT PRIMARY KEY auto_increment,
NAME varchar(50),
AGE INT,
GENDER varchar(50),
COURSE VARCHAR(50),
MARKS int
);
INSERT INTO STUDENTS (NAME, AGE, GENDER, COURSE, MARKS) VALUES
('PRABAS', 20,'MALE', 'MCA', 85),
('ANUSHKA', 22, 'FEMALE', 'MBA', 70),
('NANI', 21, 'MALE', 'BCA', 92),
('ASHOK', 23, 'MALE', 'MCA', 95);
SELECT * FROM STUDENTS
WHERE MARKS >80;
UPDATE STUDENTS
SET MARKS = 82
WHERE STUDENTID =2;
select * FROM STUDENTS;
DELETE FROM STUDENTS
WHERE STUDENTID = 1;




